<a href="https://colab.research.google.com/github/cromeflo/Programacion_en_Python_UTEC/blob/main/CLASE_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
datos_4 = np.arange(10)
datos_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(datos_4)

numpy.ndarray

In [ ]:
datos_4.min()

0

In [ ]:
datos_4.max()

9

In [ ]:
datos_4.mean()

4.5

In [ ]:
datos_4.sum()

45

In [ ]:
mat_1 = np.random.uniform(5,6,10)
mat_1

array([5.62110058, 5.58874398, 5.6046775 , 5.29657682, 5.15085204,
       5.43840699, 5.02620394, 5.42485934, 5.60154266, 5.76163751])

In [ ]:
mat_2 = np.random.uniform(1,2,10)
mat_2

array([1.14129881, 1.83137142, 1.51668801, 1.85247241, 1.63075836,
       1.60714368, 1.88060454, 1.11685017, 1.57251668, 1.21867913])

In [ ]:
mat_3 = np.random.uniform(-1,1,10)
mat_3

array([-0.32912255,  0.33697832,  0.52094512,  0.91440649, -0.75989157,
        0.43083125,  0.33322512,  0.60969754,  0.74539209,  0.68729194])

In [ ]:
mat_1.ndim

1

In [ ]:
mat_1 + mat_2 + mat_3

array([6.43327684, 7.75709372, 7.64231063, 8.06345571, 6.02171882,
       7.47638192, 7.2400336 , 7.15140705, 7.91945143, 7.66760857])

In [ ]:
# Obtener una serie a partir de una matriz (1D)
ser_mat_1 = pd.Series(mat_1)
ser_mat_1

0    5.621101
1    5.588744
2    5.604678
3    5.296577
4    5.150852
5    5.438407
6    5.026204
7    5.424859
8    5.601543
9    5.761638
dtype: float64

In [ ]:
ser_mat_2 = pd.Series(mat_2)
ser_mat_2

0    1.141299
1    1.831371
2    1.516688
3    1.852472
4    1.630758
5    1.607144
6    1.880605
7    1.116850
8    1.572517
9    1.218679
dtype: float64

In [ ]:
ser_mat_3 = pd.Series(mat_3)
ser_mat_3

0   -0.329123
1    0.336978
2    0.520945
3    0.914406
4   -0.759892
5    0.430831
6    0.333225
7    0.609698
8    0.745392
9    0.687292
dtype: float64

In [ ]:
%whos

Variable    Type       Data/Info
--------------------------------
datos_4     ndarray    10: 10 elems, type `int64`, 80 bytes
mat_1       ndarray    10: 10 elems, type `float64`, 80 bytes
mat_2       ndarray    10: 10 elems, type `float64`, 80 bytes
mat_3       ndarray    10: 10 elems, type `float64`, 80 bytes
np          module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd          module     <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
ser_mat_1   Series     0    5.621101\n1    5.588<...> 5.761638\ndtype: float64
ser_mat_2   Series     0    1.141299\n1    1.831<...> 1.218679\ndtype: float64
ser_mat_3   Series     0   -0.329123\n1    0.336<...> 0.687292\ndtype: float64


In [ ]:
ser_mat_4 = ser_mat_1 + ser_mat_2 + ser_mat_3
ser_mat_4

0    6.433277
1    7.757094
2    7.642311
3    8.063456
4    6.021719
5    7.476382
6    7.240034
7    7.151407
8    7.919451
9    7.667609
dtype: float64

In [ ]:
ser_mat_4.describe()

count    10.000000
mean      7.337274
std       0.654551
min       6.021719
25%       7.173564
50%       7.559346
75%       7.734722
max       8.063456
dtype: float64

In [ ]:
np.array(["a","b","c"])

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
pd.Series(np.array(["a","b","c"]),index=["x","y","z"])

x    a
y    b
z    c
dtype: object

In [ ]:
dict_1 = {"Serie_1": ser_mat_1,
          "Serie_2": ser_mat_2,
          "Serie_3": ser_mat_3,
          "Serie_4": ser_mat_4
          }

In [ ]:
type(dict_1)

dict

In [ ]:
dict_1

{'Serie_1': 0    5.621101
 1    5.588744
 2    5.604678
 3    5.296577
 4    5.150852
 5    5.438407
 6    5.026204
 7    5.424859
 8    5.601543
 9    5.761638
 dtype: float64,
 'Serie_2': 0    1.141299
 1    1.831371
 2    1.516688
 3    1.852472
 4    1.630758
 5    1.607144
 6    1.880605
 7    1.116850
 8    1.572517
 9    1.218679
 dtype: float64,
 'Serie_3': 0   -0.329123
 1    0.336978
 2    0.520945
 3    0.914406
 4   -0.759892
 5    0.430831
 6    0.333225
 7    0.609698
 8    0.745392
 9    0.687292
 dtype: float64,
 'Serie_4': 0    6.433277
 1    7.757094
 2    7.642311
 3    8.063456
 4    6.021719
 5    7.476382
 6    7.240034
 7    7.151407
 8    7.919451
 9    7.667609
 dtype: float64}

In [ ]:
data = pd.DataFrame(dict_1)

In [ ]:
data.head(5)

Serie_1   Serie_2   Serie_3   Serie_4
0  5.621101  1.141299 -0.329123  6.433277
1  5.588744  1.831371  0.336978  7.757094
2  5.604678  1.516688  0.520945  7.642311
3  5.296577  1.852472  0.914406  8.063456
4  5.150852  1.630758 -0.759892  6.021719

In [ ]:
data.shape

(10, 4)

In [ ]:
import sys

sys.path[0]

'/content'

In [ ]:
data_census = pd.read_csv("Data/census.csv", sep=",")

In [ ]:
type(data_census)

pandas.core.frame.DataFrame

In [ ]:
data_census.head(2)

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   

         occupation    relationship    race gender  hours_per_week  \
0      Adm-clerical   Not-in-family   White   Male              40   
1   Exec-managerial         Husband   White   Male              13   

   native_country  greater_than_50k  
0   United-States                 0  
1   United-States                 0

In [ ]:
data_census.shape

(32560, 12)

In [ ]:
data_census.shape[0] # Nro de filas del DataFrame

32560

In [ ]:
data_census.shape[1] # Nro de columnas del DataFrame

12

In [ ]:
data_census.describe()